name: Workflow for CodeCov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    run-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: SebastienRe/ceri-m1-techniques-de-test